services:
  - type: static
    name: portfolio-frontend
    plan: free
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist
    buildEnv:
      - key: VITE_API_URL
        value: https://portfolio-backend.onrender.com

  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: "3001"
      - key: CLIENT_URL
        value: https://portfolio-qf8o.onrender.com
    healthCheckPath: /health
    healthCheckTimeoutSeconds: 10
